name: f_aviation_accidents
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  intl: ^0.20.1
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/avcc_app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/icons/avcc_app_icon.png
