name: f_aviation_accidents
description: "Viewing Accident Lists and Statistical Information by Airline."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  intl: ^0.20.1
  auto_size_text: ^3.0.0
  pie_chart: ^5.4.0
  url_launcher: ^6.3.1
  google_mobile_ads: ^5.2.0
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/avcc_app_icon512.png
    - assets/icons/avcc_app_icon1024.png
    - assets/icons/avcc_app_icon_monochrome.png
    - assets/icons/avcc_app_icon_foreground.png
    - assets/icons/avcc_app_icon_round.png
